/* soapClient.cpp
   Generated by gSOAP 2.8.84 for WeatherService.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.84 2019-06-12 00:59:23 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__qqCheckOnline(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__qqCheckOnline *ns1__qqCheckOnline, _ns1__qqCheckOnlineResponse &ns1__qqCheckOnlineResponse)
{	if (soap_send___ns1__qqCheckOnline(soap, soap_endpoint, soap_action, ns1__qqCheckOnline) || soap_recv___ns1__qqCheckOnline(soap, ns1__qqCheckOnlineResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__qqCheckOnline(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__qqCheckOnline *ns1__qqCheckOnline)
{	struct __ns1__qqCheckOnline soap_tmp___ns1__qqCheckOnline;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.webxml.com.cn/webservices/qqOnlineWebService.asmx";
	if (soap_action == NULL)
		soap_action = "http://WebXml.com.cn/qqCheckOnline";
	soap_tmp___ns1__qqCheckOnline.ns1__qqCheckOnline = ns1__qqCheckOnline;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__qqCheckOnline(soap, &soap_tmp___ns1__qqCheckOnline);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__qqCheckOnline(soap, &soap_tmp___ns1__qqCheckOnline, "-ns1:qqCheckOnline", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__qqCheckOnline(soap, &soap_tmp___ns1__qqCheckOnline, "-ns1:qqCheckOnline", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__qqCheckOnline(struct soap *soap, _ns1__qqCheckOnlineResponse &ns1__qqCheckOnlineResponse)
{
	ns1__qqCheckOnlineResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__qqCheckOnlineResponse.soap_get(soap, "ns1:qqCheckOnlineResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__qqCheckOnline_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__qqCheckOnline *ns1__qqCheckOnline, _ns1__qqCheckOnlineResponse &ns1__qqCheckOnlineResponse)
{	if (soap_send___ns1__qqCheckOnline_(soap, soap_endpoint, soap_action, ns1__qqCheckOnline) || soap_recv___ns1__qqCheckOnline_(soap, ns1__qqCheckOnlineResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__qqCheckOnline_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__qqCheckOnline *ns1__qqCheckOnline)
{	struct __ns1__qqCheckOnline_ soap_tmp___ns1__qqCheckOnline_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.webxml.com.cn/webservices/qqOnlineWebService.asmx";
	if (soap_action == NULL)
		soap_action = "http://WebXml.com.cn/qqCheckOnline";
	soap_tmp___ns1__qqCheckOnline_.ns1__qqCheckOnline = ns1__qqCheckOnline;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__qqCheckOnline_(soap, &soap_tmp___ns1__qqCheckOnline_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__qqCheckOnline_(soap, &soap_tmp___ns1__qqCheckOnline_, "-ns1:qqCheckOnline", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__qqCheckOnline_(soap, &soap_tmp___ns1__qqCheckOnline_, "-ns1:qqCheckOnline", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__qqCheckOnline_(struct soap *soap, _ns1__qqCheckOnlineResponse &ns1__qqCheckOnlineResponse)
{
	ns1__qqCheckOnlineResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__qqCheckOnlineResponse.soap_get(soap, "ns1:qqCheckOnlineResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
