/* soapClient.cpp
   Generated by gSOAP 2.8.84 for MesWebservice.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.84 2019-06-12 08:07:27 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__BarCodeSend(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__BarCodeSend *ns1__BarCodeSend, _ns1__BarCodeSendResponse &ns1__BarCodeSendResponse)
{	if (soap_send___ns1__BarCodeSend(soap, soap_endpoint, soap_action, ns1__BarCodeSend) || soap_recv___ns1__BarCodeSend(soap, ns1__BarCodeSendResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__BarCodeSend(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__BarCodeSend *ns1__BarCodeSend)
{	struct __ns1__BarCodeSend soap_tmp___ns1__BarCodeSend;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.100.52/meswebservice/Print.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/BarCodeSend";
	soap_tmp___ns1__BarCodeSend.ns1__BarCodeSend = ns1__BarCodeSend;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__BarCodeSend(soap, &soap_tmp___ns1__BarCodeSend);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__BarCodeSend(soap, &soap_tmp___ns1__BarCodeSend, "-ns1:BarCodeSend", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__BarCodeSend(soap, &soap_tmp___ns1__BarCodeSend, "-ns1:BarCodeSend", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__BarCodeSend(struct soap *soap, _ns1__BarCodeSendResponse &ns1__BarCodeSendResponse)
{
	ns1__BarCodeSendResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__BarCodeSendResponse.soap_get(soap, "ns1:BarCodeSendResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__BarCodeTable(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__BarCodeTable *ns1__BarCodeTable, _ns1__BarCodeTableResponse &ns1__BarCodeTableResponse)
{	if (soap_send___ns1__BarCodeTable(soap, soap_endpoint, soap_action, ns1__BarCodeTable) || soap_recv___ns1__BarCodeTable(soap, ns1__BarCodeTableResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__BarCodeTable(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__BarCodeTable *ns1__BarCodeTable)
{	struct __ns1__BarCodeTable soap_tmp___ns1__BarCodeTable;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.100.52/meswebservice/Print.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/BarCodeTable";
	soap_tmp___ns1__BarCodeTable.ns1__BarCodeTable = ns1__BarCodeTable;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__BarCodeTable(soap, &soap_tmp___ns1__BarCodeTable);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__BarCodeTable(soap, &soap_tmp___ns1__BarCodeTable, "-ns1:BarCodeTable", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__BarCodeTable(soap, &soap_tmp___ns1__BarCodeTable, "-ns1:BarCodeTable", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__BarCodeTable(struct soap *soap, _ns1__BarCodeTableResponse &ns1__BarCodeTableResponse)
{
	ns1__BarCodeTableResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__BarCodeTableResponse.soap_get(soap, "ns1:BarCodeTableResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__BarCodeSend_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__BarCodeSend *ns1__BarCodeSend, _ns1__BarCodeSendResponse &ns1__BarCodeSendResponse)
{	if (soap_send___ns1__BarCodeSend_(soap, soap_endpoint, soap_action, ns1__BarCodeSend) || soap_recv___ns1__BarCodeSend_(soap, ns1__BarCodeSendResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__BarCodeSend_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__BarCodeSend *ns1__BarCodeSend)
{	struct __ns1__BarCodeSend_ soap_tmp___ns1__BarCodeSend_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.100.52/meswebservice/Print.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/BarCodeSend";
	soap_tmp___ns1__BarCodeSend_.ns1__BarCodeSend = ns1__BarCodeSend;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__BarCodeSend_(soap, &soap_tmp___ns1__BarCodeSend_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__BarCodeSend_(soap, &soap_tmp___ns1__BarCodeSend_, "-ns1:BarCodeSend", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__BarCodeSend_(soap, &soap_tmp___ns1__BarCodeSend_, "-ns1:BarCodeSend", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__BarCodeSend_(struct soap *soap, _ns1__BarCodeSendResponse &ns1__BarCodeSendResponse)
{
	ns1__BarCodeSendResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__BarCodeSendResponse.soap_get(soap, "ns1:BarCodeSendResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__BarCodeTable_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__BarCodeTable *ns1__BarCodeTable, _ns1__BarCodeTableResponse &ns1__BarCodeTableResponse)
{	if (soap_send___ns1__BarCodeTable_(soap, soap_endpoint, soap_action, ns1__BarCodeTable) || soap_recv___ns1__BarCodeTable_(soap, ns1__BarCodeTableResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__BarCodeTable_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__BarCodeTable *ns1__BarCodeTable)
{	struct __ns1__BarCodeTable_ soap_tmp___ns1__BarCodeTable_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.1.100.52/meswebservice/Print.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/BarCodeTable";
	soap_tmp___ns1__BarCodeTable_.ns1__BarCodeTable = ns1__BarCodeTable;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__BarCodeTable_(soap, &soap_tmp___ns1__BarCodeTable_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__BarCodeTable_(soap, &soap_tmp___ns1__BarCodeTable_, "-ns1:BarCodeTable", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__BarCodeTable_(soap, &soap_tmp___ns1__BarCodeTable_, "-ns1:BarCodeTable", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__BarCodeTable_(struct soap *soap, _ns1__BarCodeTableResponse &ns1__BarCodeTableResponse)
{
	ns1__BarCodeTableResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__BarCodeTableResponse.soap_get(soap, "ns1:BarCodeTableResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
